fix: ghrel command branch

diff --git a/home/bin/ghrel b/home/bin/ghrel
--- a/home/bin/ghrel
+++ b/home/bin/ghrel
@@ -2,9 +2,15 @@
 
 set -ue
 
+if ! git branch | grep -q '* main'; then
+    echo 'Error: Please switch to the main branch'
+    exit 1
+fi
+
 branch=$1
 
 git fetch
+git merge origin/main
 body=`git log origin/$1...origin/main --pretty=format:"%s" | grep 'Merge pull request' | grep -v 'main$' | perl -pe 's/Merge pull request //' | perl -pe 's/^/- /'`
 
 echo $body | perl -pe 's/- /\n- /g'
